# Generated by Django 5.2.7 on 2026-01-27 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0022_role_can_delete_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Feature Code')),
                ('name', models.CharField(max_length=200, verbose_name='Feature Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='pending', max_length=20, verbose_name='Status')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Auto Renew')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount Paid')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.translationcenter', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='billing.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tariff Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('max_branches', models.IntegerField(blank=True, help_text='Leave empty for unlimited', null=True, verbose_name='Max Branches')),
                ('max_staff', models.IntegerField(blank=True, help_text='Leave empty for unlimited', null=True, verbose_name='Max Staff')),
                ('max_monthly_orders', models.IntegerField(blank=True, help_text='Leave empty for unlimited', null=True, verbose_name='Max Monthly Orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, to='billing.feature', verbose_name='Features')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.tariff', verbose_name='Tariff'),
        ),
        migrations.CreateModel(
            name='TariffPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year')], verbose_name='Duration (Months)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek Sum'), ('USD', 'US Dollar'), ('RUB', 'Russian Ruble')], default='UZS', max_length=3, verbose_name='Currency')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount compared to monthly pricing', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='billing.tariff', verbose_name='Tariff')),
            ],
            options={
                'verbose_name': 'Tariff Pricing',
                'verbose_name_plural': 'Tariff Pricings',
                'ordering': ['tariff', 'duration_months'],
                'unique_together': {('tariff', 'duration_months', 'currency')},
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.tariffpricing', verbose_name='Pricing Plan'),
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('orders_created', models.IntegerField(default=0, verbose_name='Orders Created')),
                ('branches_count', models.IntegerField(default=0, verbose_name='Branches Count')),
                ('staff_count', models.IntegerField(default=0, verbose_name='Staff Count')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue')),
                ('bot_orders', models.IntegerField(default=0, verbose_name='Bot Orders')),
                ('manual_orders', models.IntegerField(default=0, verbose_name='Manual Orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='organizations.translationcenter', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Usage Tracking',
                'verbose_name_plural': 'Usage Tracking',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='billing_sub_organiz_e1331c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date', 'status'], name='billing_sub_end_dat_5372fa_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['organization', 'year', 'month'], name='billing_usa_organiz_1a2c63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagetracking',
            unique_together={('organization', 'year', 'month')},
        ),
    ]
