# Generated by Django 5.2.7 on 2026-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Is Trial Subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Trial End Date'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Free trial tariff', verbose_name='Is Trial'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='trial_days',
            field=models.IntegerField(blank=True, help_text='Duration of trial period in days (only for trial tariffs)', null=True, verbose_name='Trial Days'),
        ),
    ]
