# Generated by Django 5.2.7 on 2026-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_is_trial_subscription_trial_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='feature_advanced_security',
            field=models.BooleanField(default=False, help_text='Enhanced security (audit logs, RBAC)', verbose_name='Advanced Security Features'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_analytics_advanced',
            field=models.BooleanField(default=False, help_text='Detailed reports, financial analytics, trends', verbose_name='Advanced Analytics'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_analytics_basic',
            field=models.BooleanField(default=False, help_text='View order counts and basic statistics', verbose_name='Basic Analytics'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_api_access',
            field=models.BooleanField(default=False, help_text='REST API for custom integrations (on request)', verbose_name='REST API Access'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_archive_access',
            field=models.BooleanField(default=False, help_text='Access compressed archives of completed orders', verbose_name='Historical File Archives'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_audit_logs',
            field=models.BooleanField(default=False, help_text='Track all system actions and changes', verbose_name='Comprehensive Audit Logs'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_branch_settings',
            field=models.BooleanField(default=False, help_text='Customize settings per branch', verbose_name='Branch Settings'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_broadcast_messages',
            field=models.BooleanField(default=False, help_text='Send targeted broadcasts to customers', verbose_name='Mass Broadcast Messaging'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_bulk_payments',
            field=models.BooleanField(default=False, help_text='Process payments across multiple orders', verbose_name='Bulk Payment Processing'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_cloud_backup',
            field=models.BooleanField(default=False, help_text='Database and file backups to cloud storage', verbose_name='Automated Cloud Backups'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_custom_reports',
            field=models.BooleanField(default=False, help_text='Create custom reports with filters', verbose_name='Custom Report Builder'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_custom_roles',
            field=models.BooleanField(default=False, help_text='Create custom staff roles with RBAC', verbose_name='Custom Roles & Permissions'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_data_retention',
            field=models.BooleanField(default=False, help_text='Configure data retention policies', verbose_name='Data Retention Control'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_dynamic_pricing',
            field=models.BooleanField(default=False, help_text='Per-page pricing calculations', verbose_name='Dynamic Pricing'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_expense_tracking',
            field=models.BooleanField(default=False, help_text='Track business expenses by branch', verbose_name='Expense Tracking'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_export_reports',
            field=models.BooleanField(default=False, help_text='Export to Excel, PDF, CSV formats', verbose_name='Export Reports'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_extended_storage',
            field=models.BooleanField(default=False, help_text='Additional storage for documents and media', verbose_name='Extended Storage Capacity'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_financial_reports',
            field=models.BooleanField(default=False, help_text='Revenue, profit, expense analysis', verbose_name='Financial Reports'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_integrations',
            field=models.BooleanField(default=False, help_text='Custom integrations with external services (on request)', verbose_name='Third-Party Integrations'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_invoicing',
            field=models.BooleanField(default=False, help_text='Generate invoices for orders', verbose_name='Automated Invoicing'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_knowledge_base',
            field=models.BooleanField(default=False, help_text='Access to documentation and user guides', verbose_name='Knowledge Base Access'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_language_pricing',
            field=models.BooleanField(default=False, help_text='Different pricing per language combination', verbose_name='Language-Specific Pricing'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_marketing_basic',
            field=models.BooleanField(default=False, help_text='Create and manage marketing posts', verbose_name='Marketing Campaign Tools'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_multi_branch',
            field=models.BooleanField(default=False, help_text='Manage multiple branch locations', verbose_name='Multiple Branches'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_multi_currency',
            field=models.BooleanField(default=False, help_text='Support for multiple currencies (UZS, USD, RUB)', verbose_name='Multi-Currency Pricing'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_order_assignment',
            field=models.BooleanField(default=False, help_text='Assign orders to specific staff members', verbose_name='Order Assignment'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_order_templates',
            field=models.BooleanField(default=False, help_text='Save and reuse order configurations', verbose_name='Order Templates'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_orders_advanced',
            field=models.BooleanField(default=False, help_text='Bulk operations, advanced filters, export', verbose_name='Advanced Order Management'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_orders_basic',
            field=models.BooleanField(default=False, help_text='Create, view, and track customer orders', verbose_name='Basic Order Management'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_payment_management',
            field=models.BooleanField(default=False, help_text='Manual payment recording and receipt verification', verbose_name='Payment Tracking & Recording'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_products_advanced',
            field=models.BooleanField(default=False, help_text='Complex pricing, categories, customization', verbose_name='Advanced Product Management'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_products_basic',
            field=models.BooleanField(default=False, help_text='Manage services and basic pricing', verbose_name='Basic Product Management'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_staff_performance',
            field=models.BooleanField(default=False, help_text='Track individual staff productivity', verbose_name='Staff Performance Reports'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_staff_scheduling',
            field=models.BooleanField(default=False, help_text='Schedule and manage staff shifts', verbose_name='Staff Scheduling'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_support_tickets',
            field=models.BooleanField(default=False, help_text='Internal ticketing for issue tracking', verbose_name='Support Ticketing System'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_telegram_bot',
            field=models.BooleanField(default=False, help_text='Customer-facing bot for order placement', verbose_name='Telegram Bot Integration'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_webhooks',
            field=models.BooleanField(default=False, help_text='Configure and manage Telegram bot webhooks', verbose_name='Telegram Webhook Management'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features',
            field=models.ManyToManyField(blank=True, to='billing.feature', verbose_name='Features (Legacy)'),
        ),
    ]
