# Generated by Django 5.2.7 on 2026-02-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_unimplemented_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.tariffpricing', verbose_name='Pricing Plan'),
        ),
    ]
