# Generated by Django 5.2.7 on 2026-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_subscription_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Tariff Title'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Tariff Title'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Tariff Title'),
        ),
    ]
