# Generated by Django 5.2.7 on 2026-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_tariff_description_en_tariff_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='max_monthly_broadcasts',
            field=models.IntegerField(blank=True, help_text='Maximum marketing broadcasts per month. Leave empty for unlimited.', null=True, verbose_name='Max Monthly Broadcasts'),
        ),
        migrations.AddField(
            model_name='usagetracking',
            name='marketing_posts_sent',
            field=models.IntegerField(default=0, verbose_name='Marketing Posts Sent'),
        ),
    ]
