# Generated by Django 5.2.7 on 2026-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_tariff_max_monthly_broadcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='feature_data_retention',
            field=models.BooleanField(default=False, help_text='Configure data retention and archival rules', verbose_name='Data Retention Policies'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_invoicing',
            field=models.BooleanField(default=False, help_text='Generate and manage invoices for customers', verbose_name='Invoicing'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_knowledge_base',
            field=models.BooleanField(default=False, help_text='Access to documentation and help articles', verbose_name='Knowledge Base'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_order_templates',
            field=models.BooleanField(default=False, help_text='Pre-defined templates for common order types', verbose_name='Order Templates'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_staff_scheduling',
            field=models.BooleanField(default=False, help_text='Schedule and manage staff work shifts', verbose_name='Staff Scheduling'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_support_tickets',
            field=models.BooleanField(default=False, help_text='Built-in support ticket management system', verbose_name='Support Tickets'),
        ),
    ]
