# Generated by Django 5.2.7 on 2026-03-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_missing_feature_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='feature_advanced_security',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_cloud_backup',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_data_retention',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_extended_storage',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_knowledge_base',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_multi_currency',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_order_templates',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_staff_scheduling',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='feature_support_tickets',
        ),
    ]
