# Generated by Django 5.2.7 on 2026-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_stub_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='feature_agency_management',
            field=models.BooleanField(default=False, help_text='Create and manage B2B agency partners with agency-specific pricing', verbose_name='Agency Management'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_debt_tracking',
            field=models.BooleanField(default=False, help_text='Unit economy analytics: outstanding balances, top debtors, collection rates', verbose_name='Debt & Receivables Tracking'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_extra_fees',
            field=models.BooleanField(default=False, help_text='Add manual surcharges or price corrections to existing orders', verbose_name='Order Extra Fees'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='feature_general_expenses',
            field=models.BooleanField(default=False, help_text='Track operational costs: rent, salaries, stationery, repairs — not tied to individual orders', verbose_name='General (Operating) Expenses'),
        ),
    ]
