# Generated by ChatGPT on 2026-03-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_subscriptionhistory_admin_bot_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(default=False, verbose_name="Auto Renew"),
        ),
    ]
