# Generated by Django 5.2.7 on 2026-01-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_notification_types'),
        ('organizations', '0020_role_can_create_languages_role_can_edit_languages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_name', models.CharField(help_text='Name of the archive file', max_length=255, verbose_name='Archive Name')),
                ('archive_path', models.CharField(blank=True, help_text='Path to archive file if still stored locally', max_length=500, null=True, verbose_name='Local Archive Path')),
                ('telegram_message_id', models.BigIntegerField(help_text='Message ID in Telegram channel where archive is stored', verbose_name='Telegram Message ID')),
                ('telegram_channel_id', models.CharField(help_text='Channel ID where archive is uploaded', max_length=100, verbose_name='Telegram Channel ID')),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Number of orders included in archive', verbose_name='Total Orders')),
                ('total_size_bytes', models.BigIntegerField(default=0, help_text='Total size of archived files in bytes', verbose_name='Total Size (bytes)')),
                ('archive_date', models.DateTimeField(auto_now_add=True, help_text='When the archive was created', verbose_name='Archive Date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this archive', verbose_name='Notes')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_archives', to='organizations.translationcenter', verbose_name='Center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_archives', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'File Archive',
                'verbose_name_plural': 'File Archives',
                'ordering': ['-archive_date'],
                'indexes': [models.Index(fields=['center', '-archive_date'], name='core_filear_center__084bee_idx'), models.Index(fields=['telegram_message_id'], name='core_filear_telegra_dac400_idx')],
            },
        ),
    ]
