# Generated by Django 5.2.7 on 2026-01-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_filearchive'),
    ]

    operations = [
    ]
