# Generated by Django 5.2.7 on 2026-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('pending', 'Pending'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
