# Generated by Django 5.2.7 on 2025-12-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_bot_channel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_marketing_posts',
            field=models.BooleanField(default=False, verbose_name='Can create marketing posts'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_send_branch_broadcasts',
            field=models.BooleanField(default=False, verbose_name='Can send branch broadcasts'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_send_center_broadcasts',
            field=models.BooleanField(default=False, verbose_name='Can send center-wide broadcasts'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_broadcast_stats',
            field=models.BooleanField(default=False, verbose_name='Can view broadcast statistics'),
        ),
    ]
