# Generated by Django 5.2.7 on 2025-12-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_add_marketing_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_manage_branch_settings",
            field=models.BooleanField(
                default=False,
                help_text="Can edit branch payment info, help texts, about us, working hours",
                verbose_name="Can manage branch settings",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_view_branch_settings",
            field=models.BooleanField(
                default=False,
                help_text="Can view branch settings without editing",
                verbose_name="Can view branch settings",
            ),
        ),
    ]
