# Generated by Django 5.2.7 on 2025-12-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0015_add_audit_log_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationcenter",
            name="bot_username",
            field=models.CharField(
                blank=True,
                help_text="Telegram Bot username without @ (e.g., 'my_translation_bot')",
                max_length=100,
                null=True,
                verbose_name="Bot Username",
            ),
        ),
    ]
