# Generated by Django 5.2.7 on 2026-01-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_role_can_create_expenses_role_can_delete_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_assign_bulk_payment_permission',
            field=models.BooleanField(default=False, help_text='Can grant the bulk payment permission to other users', verbose_name='Can assign bulk payment permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_bulk_payments',
            field=models.BooleanField(default=False, help_text='Can process bulk payments for customer/agency debts across multiple orders', verbose_name='Can manage bulk payments'),
        ),
    ]
