# Generated by Django 5.2.7 on 2026-01-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_role_can_create_languages_role_can_edit_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationcenter',
            name='company_orders_channel_id',
            field=models.CharField(blank=True, help_text='Telegram channel ID for all company orders and file archives', max_length=50, null=True, verbose_name='Company Orders Channel ID'),
        ),
    ]
