# Generated by Django 5.2.7 on 2026-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_bot_delivery_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationcenter',
            name='workflow_automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable quote and automatic assignment workflows for this pilot center.', verbose_name='Workflow Automation Enabled'),
        ),
    ]
