# Generated by Django 5.2.7 on 2025-12-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='broadcastrecipient',
            new_name='marketing_b_post_id_95de66_idx',
            old_name='marketing_b_post_id_8f6c3e_idx',
        ),
        migrations.RenameIndex(
            model_name='broadcastrecipient',
            new_name='marketing_b_bot_use_0b346e_idx',
            old_name='marketing_b_bot_use_3e8e0e_idx',
        ),
    ]
