# Generated by Django 5.2.7 on 2025-12-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_add_branch_settings_permissions'),
        ('services', '0002_category_branch_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Expense Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of this expense', max_digits=12, verbose_name='Price')),
                ('expense_type', models.CharField(choices=[('b2b', 'B2B (Agency/Business)'), ('b2c', 'B2C (Individual Customer)'), ('both', 'Both B2B & B2C')], default='both', help_text='Whether this expense applies to B2B, B2C, or both', max_length=10, verbose_name='Expense Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('branch', models.ForeignKey(help_text='Branch this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='organizations.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='expenses',
            field=models.ManyToManyField(blank=True, help_text='Expenses associated with this product', related_name='products', to='services.expense', verbose_name='Expenses'),
        ),
    ]
