# Generated by Django 5.2.7 on 2026-01-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_expense_product_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agency_copy_price_decimal',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, help_text='Decimal multiplier for agency copy price (e.g., 1.0 = 100%, 1.5 = 150%). If set, this overrides agency_copy_price_percentage.', max_digits=5, null=True, verbose_name='Agency Copy Price Multiplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_copy_price_decimal',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, help_text='Decimal multiplier for user copy price (e.g., 1.0 = 100%, 1.5 = 150%). If set, this overrides user_copy_price_percentage.', max_digits=5, null=True, verbose_name='User Copy Price Multiplier'),
        ),
    ]
