# Generated by Django 5.2.7 on 2026-01-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_product_agency_copy_price_decimal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agency_copy_price_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fixed price per copy for agencies (e.g., 25000 = 25,000 UZS per copy). If set, this overrides agency_copy_price_percentage.', max_digits=10, null=True, verbose_name='Agency Copy Price (Fixed)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_copy_price_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fixed price per copy for users (e.g., 30000 = 30,000 UZS per copy). If set, this overrides user_copy_price_percentage.', max_digits=10, null=True, verbose_name='User Copy Price (Fixed)'),
        ),
    ]
