# Generated by Django 5.2.7 on 2026-01-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_language_pricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Til', 'verbose_name_plural': 'Tillar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Hujjat turi', 'verbose_name_plural': 'Document Types'},
        ),
    ]
