# Generated by Django 5.2.7 on 2025-12-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("organizations", "0008_add_marketing_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_card",
                    models.CharField(
                        blank=True,
                        help_text="Card number for receiving payments (e.g., 8600 1234 5678 9012)",
                        max_length=20,
                        null=True,
                        verbose_name="Bank Card Number",
                    ),
                ),
                (
                    "holder_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the card holder",
                        max_length=100,
                        null=True,
                        verbose_name="Card Holder Name",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Help text shown in bot",
                        null=True,
                        verbose_name="Help Text",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the branch/center",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "about_us",
                    models.TextField(
                        blank=True,
                        help_text="About us information",
                        null=True,
                        verbose_name="About Us",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Mon-Fri: 9:00-18:00, Sat: 10:00-15:00",
                        max_length=200,
                        null=True,
                        verbose_name="Working Hours",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for customer support",
                        max_length=20,
                        null=True,
                        verbose_name="Support Phone",
                    ),
                ),
                (
                    "support_telegram",
                    models.CharField(
                        blank=True,
                        help_text="Telegram username for support (e.g., @support_bot)",
                        max_length=100,
                        null=True,
                        verbose_name="Support Telegram",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "branch",
                    models.OneToOneField(
                        blank=True,
                        help_text="Leave empty for global/default settings",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to="organizations.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Info",
                "verbose_name_plural": "Additional Info",
            },
        ),
    ]
