# Generated by Django 5.2.7 on 2025-12-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_additional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalinfo",
            name="about_us_en",
            field=models.TextField(
                blank=True,
                help_text="About us information",
                null=True,
                verbose_name="About Us",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="about_us_ru",
            field=models.TextField(
                blank=True,
                help_text="About us information",
                null=True,
                verbose_name="About Us",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="about_us_uz",
            field=models.TextField(
                blank=True,
                help_text="About us information",
                null=True,
                verbose_name="About Us",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the branch/center",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Description of the branch/center",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="description_uz",
            field=models.TextField(
                blank=True,
                help_text="Description of the branch/center",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="help_text_en",
            field=models.TextField(
                blank=True,
                help_text="Help text shown in bot",
                null=True,
                verbose_name="Help Text",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="help_text_ru",
            field=models.TextField(
                blank=True,
                help_text="Help text shown in bot",
                null=True,
                verbose_name="Help Text",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="help_text_uz",
            field=models.TextField(
                blank=True,
                help_text="Help text shown in bot",
                null=True,
                verbose_name="Help Text",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="working_hours_en",
            field=models.CharField(
                blank=True,
                help_text="e.g., Mon-Fri: 9:00-18:00, Sat: 10:00-15:00",
                max_length=200,
                null=True,
                verbose_name="Working Hours",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="working_hours_ru",
            field=models.CharField(
                blank=True,
                help_text="e.g., Mon-Fri: 9:00-18:00, Sat: 10:00-15:00",
                max_length=200,
                null=True,
                verbose_name="Working Hours",
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="working_hours_uz",
            field=models.CharField(
                blank=True,
                help_text="e.g., Mon-Fri: 9:00-18:00, Sat: 10:00-15:00",
                max_length=200,
                null=True,
                verbose_name="Working Hours",
            ),
        ),
    ]
