# Generated by Django 5.2.7 on 2025-12-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_additionalinfo_about_us_en_and_more"),
        ("organizations", "0009_add_branch_settings_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="center",
            field=models.ForeignKey(
                blank=True,
                help_text="The center this user belongs to. Same Telegram user can have separate accounts per center.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_users",
                to="organizations.translationcenter",
                verbose_name="Translation Center",
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram User ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="botuser",
            unique_together={("user_id", "center")},
        ),
        migrations.AddConstraint(
            model_name="botuser",
            constraint=models.UniqueConstraint(
                fields=("user_id", "center"), name="unique_user_per_center"
            ),
        ),
    ]
