# Generated by Django 5.2.7 on 2026-03-13 09:28

import django.db.models.deletion
import support.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0026_translationcenter_payme_secret_key_prod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Name (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (EN)')),
                ('icon', models.CharField(default='solar:ticket-bold', help_text='Iconify icon name, e.g. solar:bug-bold', max_length=100, verbose_name='Icon')),
                ('color', models.CharField(default='primary', help_text='Bootstrap color: primary, success, warning, danger, info', max_length=20, verbose_name='Color')),
                ('telegram_group_id', models.CharField(blank=True, help_text='Telegram group ID where tickets in this category are routed', max_length=50, null=True, verbose_name='Telegram Group ID')),
                ('sla_hours', models.PositiveIntegerField(default=72, help_text='Ticket auto-resolves after this many hours without a staff reply', verbose_name='SLA Hours')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='organizations.translationcenter', verbose_name='Center')),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='Ticket Number')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('awaiting_staff', 'Awaiting Staff Response'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20, verbose_name='Priority')),
                ('ticket_type', models.CharField(choices=[('bug', 'Bug / Error'), ('financial', 'Financial'), ('technical', 'Technical'), ('cr', 'Change Request'), ('general', 'General Inquiry')], default='general', max_length=20, verbose_name='Type')),
                ('telegram_message_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Message ID')),
                ('telegram_group_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Group ID')),
                ('auto_resolve_at', models.DateTimeField(blank=True, null=True, verbose_name='Auto Resolve At')),
                ('has_unread_reply', models.BooleanField(default=False, verbose_name='Has Unread Support Reply')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organizations.translationcenter', verbose_name='Center')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.ticketcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('staff', 'Staff'), ('support', 'Support'), ('system', 'System')], max_length=10, verbose_name='Sender Type')),
                ('body', models.TextField(verbose_name='Message')),
                ('is_internal_note', models.BooleanField(default=False, help_text='Internal notes are visible to support only, not to the ticket creator', verbose_name='Internal Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=support.models.ticket_attachment_upload_path, verbose_name='File')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original Filename')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='From Status')),
                ('to_status', models.CharField(max_length=20, verbose_name='To Status')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='support.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['center', 'status', 'created_at'], name='support_tic_center__b5b7ee_idx'),
        ),
    ]
