# Generated by Django 5.2.7 on 2026-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='telegram_thread_id',
            field=models.CharField(blank=True, help_text='Forum topic thread ID inside the support group', max_length=50, null=True, verbose_name='Telegram Thread ID'),
        ),
    ]
