"""
Django settings for WowDash project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import logging  # Required for custom UTF8StreamHandler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ── Sentry error monitoring ──────────────────────────────────────────────────
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

_SENTRY_DSN = os.getenv("SENTRY_DSN")
if _SENTRY_DSN:
    def _sentry_before_send(event, hint):
        """
        Suppress expected Telegram polling ReadTimeout events.
        ReadTimeout on api.telegram.org is normal long-polling behaviour —
        the server returns nothing when there are no updates within the window.
        Logging it at ERROR (pyTelegramBotAPI default) would flood Sentry.
        """
        exc_info = hint.get("exc_info")
        if exc_info:
            _, exc_value, _ = exc_info
            exc_str = str(exc_value)
            if "api.telegram.org" in exc_str and (
                "Read timed out" in exc_str or "ReadTimeout" in type(exc_value).__name__
            ):
                return None
        # Also suppress when the error arrives as a log-record (LoggingIntegration path)
        log_record = hint.get("log_record")
        if log_record:
            msg = log_record.getMessage()
            if ("Read timed out" in msg or "ReadTimeout" in msg) and "api.telegram.org" in msg:
                return None
        return event

    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        environment=os.getenv("SENTRY_ENVIRONMENT", "production"),
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                level=logging.INFO,        # Breadcrumbs from INFO and above
                event_level=logging.ERROR, # Send events for ERROR and above
            ),
        ],
        before_send=_sentry_before_send,
        traces_sample_rate=0.1,   # 10 % of transactions for performance monitoring
        send_default_pii=False,   # Do not attach user PII to events
        release=os.getenv("SENTRY_RELEASE"),  # Optional: set via CI/deploy
    )
# ─────────────────────────────────────────────────────────────────────────────

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "77.42.31.194", "multilang.uz", ".multilang.uz"]
    
# CSRF trusted origins for ngrok and production
CSRF_TRUSTED_ORIGINS = [
    "https://multilang.uz",
    "https://*.multilang.uz",
]

# Main domain for subdomain extraction
MAIN_DOMAIN = os.getenv("MAIN_DOMAIN", "multilang.uz")

# ── Support ticketing — dedicated bot & group ────────────────────────────────
# This bot sends all support ticket notifications to the central support group.
# The same token is reused from ADMIN_BOT_TOKEN in .env.
SUPPORT_BOT_TOKEN = os.getenv("ADMIN_BOT_TOKEN", "")
SUPPORT_TELEGRAM_GROUP_ID = os.getenv("SUPPORT_TELEGRAM_GROUP_ID", "")
# Base URL used for dashboard deep-links in Telegram notifications
BASE_URL = os.getenv("BASE_URL", f"https://admin.{os.getenv('MAIN_DOMAIN', 'multilang.uz')}")
# ─────────────────────────────────────────────────────────────────────────────


# Application definition

INSTALLED_APPS = [
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "organizations",
    "accounts",
    "services",
    "bot",
    "orders",
    "marketing",
    "landing",
    "billing",
    "webapp",
    "support",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "landing.middleware.RateLimitMiddleware",  # Per-IP throttling for public contact form
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Language detection and activation
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "organizations.middleware.SubdomainMiddleware",  # Subdomain-based tenant identification
    "organizations.rbac.RBACMiddleware",
    "billing.middleware.SubscriptionEnforcementMiddleware",
]

ROOT_URLCONF = "WowDash.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "organizations.context_processors.rbac_context",
                "organizations.context_processors.site_settings",
                "landing.context_processors.contact_requests_count",
                "billing.context_processors.billing_context",  # Billing & subscription context
                "support.context_processors.unread_support_replies",
            ],
        },
    },
]

WSGI_APPLICATION = "WowDash.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.getenv("USE_POSTGRES", "False").lower() == "true":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "postgres"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", "password"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "uz"

LANGUAGES = [
    ("uz", "O'zbekcha"),
    ("ru", "Русский"),
    ("en", "English"),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# CACHE CONFIGURATION (Redis for multi-worker support)
# =============================================================================
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")

if os.getenv("USE_REDIS", "False").lower() == "true":
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # hiredis is automatically used when installed (redis>=5.0)
                "CONNECTION_POOL_KWARGS": {"max_connections": 50},
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
            },
            "KEY_PREFIX": "wowdash",
        }
    }
    # Use Redis for sessions in production
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Development: use local memory cache
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Modeltranslation settings
MODELTRANSLATION_DEFAULT_LANGUAGE = "uz"
MODELTRANSLATION_LANGUAGES = ("uz", "ru", "en")
MODELTRANSLATION_TRANSLATION_FILES = (
    "accounts.translations",
    "billing.translations",
    "core.translations",
    "services.translations",
)
MODELTRANSLATION_FALLBACK_LANGUAGES = ("uz", "ru", "en")
MODELTRANSLATION_PREPOPULATE_LANGUAGE = "uz"
# Auto-populate translation fields when language changes
MODELTRANSLATION_AUTO_POPULATE = False

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")
# Media files (User uploaded files)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# =============================================================================
# Payme configuration (set via environment variables)
# =============================================================================
PAYME_MERCHANT_ID = os.getenv("PAYME_MERCHANT_ID", "")
PAYME_SECRET_KEY = os.getenv("PAYME_SECRET_KEY", "")  # Used for Authorization header validation
PAYME_USE_SANDBOX = os.getenv("PAYME_USE_SANDBOX", "true").lower() == "true"
PAYME_CALLBACK_URL = os.getenv("PAYME_CALLBACK_URL", "")  # Payme JSON-RPC webhook endpoint (public URL)
PAYME_RETURN_URL = os.getenv("PAYME_RETURN_URL", "")  # Optional user redirect URL after checkout
PAYME_PAYMENT_DEADLINE_HOURS = int(os.getenv("PAYME_PAYMENT_DEADLINE_HOURS", "12"))  # Hours before payment_pending Payme order is auto-cancelled


# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
# Dedicated queue for broadcasts so heavy tasks don't starve lighter ones
CELERY_TASK_ROUTES = {
    "marketing.send_broadcast": {"queue": "broadcasts"},
}

# =============================================================================
# FIELD ENCRYPTION KEY (for sensitive DB fields: bot_token, payme keys)
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Store the generated key in .env as FIELD_ENCRYPTION_KEY=...
# =============================================================================
FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY", "")

# =============================================================================
# Authentication settings
LOGIN_URL = 'admin_login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'admin_login'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# Custom UTF-8 StreamHandler for Windows console
import sys
import codecs

class UTF8StreamHandler(logging.StreamHandler):
    """StreamHandler that forces UTF-8 encoding on Windows"""
    def __init__(self, stream=None):
        if stream is None:
            stream = sys.stdout
        # Wrap stream with UTF-8 encoding
        if hasattr(stream, 'buffer'):
            stream = codecs.getwriter('utf-8')(stream.buffer, 'replace')
        super().__init__(stream)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'standard': {
            'format': '{levelname} {asctime} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        # Machine-readable JSON formatter for structured log ingestion
        # (e.g., LogStash, Loki, or any ELK-compatible pipeline).
        # Enabled when python-json-logger is installed; silently falls back
        # to the 'standard' formatter otherwise.
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(module)s %(message)s',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            '()': 'WowDash.settings.UTF8StreamHandler',  # Use custom UTF-8 handler
            'formatter': 'standard',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'error.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Fix Unicode encoding issues
        },
        'file_audit': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'audit.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'standard',
            'encoding': 'utf-8',  # Fix Unicode encoding issues
        },
        'file_bot': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'bot.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',  # Fix Unicode encoding issues
        },
        'file_orders': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'orders.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',  # Fix Unicode encoding issues
        },
        'file_payments': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'payments.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',  # Fix Unicode encoding issues
        },
        'file_marketing': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'marketing.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',  # Fix Unicode encoding issues
        },
        # JSON-format logs for structured ingestion (orders + payments + bot)
        'file_orders_json': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'orders.json.log',
            'maxBytes': 20 * 1024 * 1024,  # 20 MB
            'backupCount': 5,
            'formatter': 'json',
            'encoding': 'utf-8',
        },
        'file_payments_json': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'payments.json.log',
            'maxBytes': 20 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'json',
            'encoding': 'utf-8',
        },
        'file_bot_json': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'bot.json.log',
            'maxBytes': 20 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'json',
            'encoding': 'utf-8',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    'loggers': {
        # Django loggers
        'django': {
            'handlers': ['console', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file_error', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file_error', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Application loggers
        'accounts': {
            'handlers': ['console', 'file_audit', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'orders': {
            'handlers': ['console', 'file_orders', 'file_orders_json', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'orders.payment_service': {
            'handlers': ['console', 'file_payments', 'file_payments_json', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'organizations': {
            'handlers': ['console', 'file_audit', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'services': {
            'handlers': ['console', 'file_audit', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'marketing': {
            'handlers': ['console', 'file_marketing', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'bot': {
            'handlers': ['console', 'file_bot', 'file_bot_json', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file_audit', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.audit': {
            'handlers': ['console', 'file_audit'],
            'level': 'INFO',
            'propagate': False,
        },
        # Audit logger for critical actions
        'audit': {
            'handlers': ['console', 'file_audit'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_error'],
        'level': 'WARNING',
    },
}