# Generated by Django 5.2.7 on 2025-12-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("services", "0002_category_branch_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="The target language selected by user from category's available languages",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.language",
                verbose_name="Translation Language",
            ),
        ),
    ]
