# Generated by Django 5.2.7 on 2025-12-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_bot_user_state"),
        ("orders", "0005_increase_file_field_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="manual_first_name",
            field=models.CharField(
                blank=True,
                help_text="Customer first name for manual orders",
                max_length=100,
                null=True,
                verbose_name="First Name",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="manual_last_name",
            field=models.CharField(
                blank=True,
                help_text="Customer last name for manual orders",
                max_length=100,
                null=True,
                verbose_name="Last Name",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="manual_phone",
            field=models.CharField(
                blank=True,
                help_text="Customer phone number for manual orders",
                max_length=20,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="bot_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for manual orders",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.botuser",
                verbose_name="Telegram User",
            ),
        ),
    ]
