# Generated by Django 5.2.7 on 2025-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_manual_first_name_order_manual_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("payment_pending", "Awaiting"),
                    ("payment_received", "Received"),
                    ("payment_confirmed", "Confirmed"),
                    ("in_progress", "In Process"),
                    ("ready", "Ready"),
                    ("completed", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
