# Generated by Django 5.2.7 on 2026-01-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_bot_user_state'),
        ('orders', '0010_add_center_order_numbering'),
        ('organizations', '0018_role_can_create_expenses_role_can_delete_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount received from customer', max_digits=12, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('other', 'Other')], default='cash', max_length=20, verbose_name='Payment Method')),
                ('receipt_note', models.TextField(blank=True, help_text='Transaction ID, receipt number, or any additional notes', null=True, verbose_name='Receipt/Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('orders_count', models.PositiveIntegerField(default=0, help_text='Number of orders this payment was applied to', verbose_name='Orders Paid')),
                ('fully_paid_orders', models.PositiveIntegerField(default=0, help_text='Number of orders that were fully paid by this transaction', verbose_name='Fully Paid Orders')),
                ('remaining_debt_after', models.DecimalField(decimal_places=2, default=0, help_text='Customer remaining debt after this payment', max_digits=12, verbose_name='Remaining Debt After')),
                ('bot_user', models.ForeignKey(blank=True, help_text='The customer/agency who made the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_payments', to='accounts.botuser', verbose_name='Customer')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch where payment was processed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_payments', to='organizations.branch', verbose_name='Branch')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin user who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_bulk_payments', to='organizations.adminuser', verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Bulk Payment',
                'verbose_name_plural': 'Bulk Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, help_text='Portion of bulk payment applied to this order', max_digits=12, verbose_name='Amount Applied')),
                ('previous_received', models.DecimalField(decimal_places=2, default=0, help_text='Order received amount before this payment', max_digits=12, verbose_name='Previous Amount Received')),
                ('new_received', models.DecimalField(decimal_places=2, default=0, help_text='Order received amount after this payment', max_digits=12, verbose_name='New Amount Received')),
                ('fully_paid', models.BooleanField(default=False, help_text='Whether this order was fully paid by this transaction', verbose_name='Fully Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='orders.bulkpayment', verbose_name='Bulk Payment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment-Order Link',
                'verbose_name_plural': 'Payment-Order Links',
                'ordering': ['bulk_payment', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkpayment',
            index=models.Index(fields=['-created_at'], name='orders_bulk_created_fc1747_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkpayment',
            index=models.Index(fields=['bot_user', '-created_at'], name='orders_bulk_bot_use_cd2737_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkpayment',
            index=models.Index(fields=['branch', '-created_at'], name='orders_bulk_branch__955e15_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorderlink',
            index=models.Index(fields=['bulk_payment'], name='orders_paym_bulk_pa_94da25_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorderlink',
            index=models.Index(fields=['order'], name='orders_paym_order_i_294eae_idx'),
        ),
    ]
