# Generated by Django 5.2.7 on 2026-01-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_filearchive'),
        ('orders', '0011_bulkpayment_paymentorderlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_files',
            field=models.ForeignKey(blank=True, help_text="Reference to archive containing this order's files", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.filearchive', verbose_name='Archived Files'),
        ),
    ]
