# Generated by Django 5.2.7 on 2026-01-25 12:31

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_telegram_file_id_to_ordermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedia',
            name='file',
            field=models.FileField(max_length=500, upload_to=orders.models.order_media_upload_path, verbose_name='File'),
        ),
    ]
