# Generated by Django 5.2.7 on 2026-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_bot_user_state'),
        ('core', '0010_archive_tracking'),
        ('orders', '0027_workflow_automation'),
        ('organizations', '0028_bot_delivery_controls'),
        ('services', '0015_add_branch_to_language'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_to', 'status', 'deadline'], name='ord_assignee_status_deadline'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['bot_user', 'status', '-created_at'], name='ord_customer_status_created'),
        ),
    ]
